### ISSUE TITLE
"Source" domain object search and view

### ISSUE THREAD

**Issue by sehrgut** [Bauble/bauble.classic#166]
"Source" metadata is unavailable outside of reporting. It makes it difficult to find sources, examine the notes about them; and makes it impossible to edit them outside of direct database queries.

**Comment by mfrasca** [comment]
see also #206

**Comment by mfrasca** [comment]
@sehrgut : I'm going to have a look at this one, but can you give a few concrete examples? this is a part where I've not yet laid my hands upon, so I need to see how you're using it. screenshots of the process you are following together with the terms you use to describe what you see, that could be enough or at least a good starting point.

**Comment by mfrasca** [comment]
@sehrgut I'm afraid we were trapped in some naming confusion in Bauble and some missing documentation. and since we're talking of documentation, I alert also @RoDuth .

My hint is to look at `Source` as an optional section of an `Accession`. when you add a source to an accession you are stating that you are going to use this optional part. in this sense it makes little sense to edit a source separately from an accession. 
in particular, a `Source` object associated to an accession adds to it a link to a `SourceDetail`. and to complete the sketch, `SourceDetail` can be queried from the QueryBuilder as `contact`. (but the domain search strategy will accept also 'org', 'person', and 'source' as synonyms for 'contact'.)

in this sense, there is no issue except "I don't understand how Bauble wants me to refer to my contacts".

maybe we could edit a couple of labels that refer to the contact name and let them display '**Contact**'. now we have in the source expander in the accession infobox a label 'Name'  and in the source tab in the accession editor a label 'Source'. maybe this would help making things a bit more self-documenting.

I also think we miss an "Insert → Contact" in the insert menu.

**Comment by mfrasca** [comment]
have been reviewing this, comparing to ITF2. apparently most of these fields come from the standard, and I've marked them now as such, also in the form of tooltips. in ITF2 terminology, we are now looking at **Donor**. and yes, yet an other name for the same thing! according to the commits, Bauble was internally using the standard terminology until about 2009.
if any of you insists, I can rename Contact to Donor. the rationale behind this would be that the ITF2 document uses Donor, not Contact nor SourceDetails. on the other hand, a contact acts as a donor when they donate something. before a donation a contact is just a contact.

**Comment by RoDuth** [comment]
I wonder if it was the changes made for UBC that may have caused the breaks from the standard?  (I remember a time when there were 2 version of Bauble, one the standard, the other the UBC version.  I'm assuming they would have been merged at some point?)  This is the sort of thing I was talking about when in issue #163 I said 
>
One of the things I have seen in the past is "drift" from the standards. i.e. a database that was once designed as ITF2 compliant that over time, due to well meaning users, who are not aware of the standards, modifying it to add extra values...

I see they now use IrisBG? Which I believe is very much to standard.  (and lets face it I don't know of any other BG specific data solutions that aren't, I mean they have their extra fields but when its the standard fields they stick to it)
I think if the original intent was to stick to the standard donor field we should do just that.  Happy for there to be the alternatives for every day users in the search strategies (e.g.  'org', 'person', and 'source' as synonyms for 'contact'... Another one I didn't know about!) or even the labels but the fields themselves should be known in the background at least by their (ITF2, ABCD, etc.) standard name so that any future developers find it easy to link it to respective standard.  I'm sure this wrong naming sort of thing has made it harder for you @mfrasca in the past?  And, as you have done, the tooltips should point users to them too.  But I'm not a developer so I don't know if I'm right here so I'll leave the decision to you @mfrasca but I would have thought that to attract any further developers to the project you should make it easy for them to get started and clearly set guidelines that follow established standards and best practice would be a part of that?  Am I wrong?

**Comment by mfrasca** [comment]
> I would have thought that to attract any further developers to the project you should make it easy for them to get started and clearly set guidelines that follow established standards and best practice would be a part of that?

I totally agree with your thought. it's just a huge amount of work to do this at this stage. I'm available to do this inside of a group, it's a lot easier when two look at each other's work, being clear all criticism comes in order to have a better product.

**Comment by RoDuth** [comment]
Good thinking with the ITF2 comments. And I can appreciate that it would consume a lot of time and is a little difficult without others to bounce off.
