### ISSUE TITLE
Species info pane no longer present

### ISSUE THREAD

**Issue by RoDuth** [Bauble/bauble.classic#168]
Hi Mario,
Thought I would open up another issue I mentioned in an email a while back.  
The right hand pane that normally has information, links to search, etc. doesn't appear at the species level in the new version.  I have installed it recently on Ubuntu 14.04, Linux Mint 17.02, OSX and Windows 10 and they all appear to have the same issue.  I'll attach 2 screen-shots from my installation in Ubuntu to explain.  First shows what I get when selecting an accession, second when selecting a species.  Curiously it does display a picture if one is present.
![screenshot ubuntu 14 04 2](https://cloud.githubusercontent.com/assets/15710055/11018366/eacaeacc-8611-11e5-88d2-fdbd3c1220f9.png)
![screenshot ubuntu 14 04](https://cloud.githubusercontent.com/assets/15710055/11018367/f7a9fbac-8611-11e5-9dc8-61730bf5fcf4.png)

**Comment by mfrasca** [comment]
the logfile associated to the above behaviour.
[bauble.log.txt](https://github.com/Bauble/bauble.classic/files/30922/bauble.log.txt)

**Comment by RoDuth** [comment]
@mfrasca, its happened again!  I did a `bauble -u` update and its disappeared again!!  Had to tweak the following lines of code in `species.py` to get it working again.  Did a recent commit put it back?
```python
class SpeciesInfoBox(InfoBox):

    def __init__(self):
        super(SpeciesInfoBox, self).__init__()  # RD removed tabbed=True
        page = SpeciesInfoPage()
        label = page.label
        if isinstance(label, basestring):
            label = gtk.Label(label)
        self.insert_page(page, label, 0)

#RD      from bauble.plugins.picasa import PicasaInfoPage
#        page = PicasaInfoPage()
#        label = page.label
#        if isinstance(label, basestring):
#            label = gtk.Label(label)
#        self.insert_page(page, label, 1)
```

**Comment by mfrasca** [comment]
I'm afraid I did not yet publish the patches in the production line.
https://github.com/Bauble/bauble.classic/network

I did not do so partially because other errors have been reported,
important enough to tell me "do not dare publish me in this form!", but
also because the old picasa pictures pane could be re-used instead of
dumped away.

the point is that we now have a second pictures-box next to the
info-box. I am not sure I (our users) like it this way, or whether I
should put the pictures back in the pictures tab of the info-box.

but in fact, as it is now, it's better than 1.0.52.

so the points have been noted and I'm going to publish the correction.

:)

MF
