### ISSUE TITLE
add 'unused' column to home screen

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#244]
in a comment to #224 @RoDuth writes:
> With this simple list you immediately have 10 of the most common searches to get into the data, just one click away. This is why I was thinking that an "unused" (or "Empty") column would be handy also, it would add another 4 searches (species, accessions, plants, locations - families and genera being greyed out) that would be very handy to me at least.
> [...] I know that its a little "double handling" but because they are hyper-links to the relevant search I can see it being very useful.

**Comment by mfrasca** [comment]
I am not so much in favour of an extra column... I can try, but I fear cluttering.
adding an extra column would also mean we either put three columns too for the stored queries buttons (this **would** mean cluttering), or we organize them in two columns while we have two columns above (also not so tidy - and a bit a complication for me to organize it.)

**Comment by mfrasca** [comment]
I am posting the screenshot, but I think I dislike the idea.
it's just because we want the four links... I'd rather put them into 4 stored queries and if we later find that the 6 remaining slots for stored queries is too little, we reconsider.
![screenshot from 2015-12-30 21 15 43](https://cloud.githubusercontent.com/assets/122869/12060297/8802df74-af3a-11e5-8d89-bc37e2d9eb32.png)
but I will commit the glade file (and revert it) just we don't loose it.

**Comment by RoDuth** [comment]
I kind of like it!   I just swapped the glade file on my set-up here and it didn't feel too cluttered to me. I think I must be running at a higher resolution than you maybe as everything gets a little lost in the top corner for me as it is.  But is it worth the extra functionality?  I don't know, maybe your right?  What about this comment from #224, I was considering raising it as a separate issue but having seen this now I'm thinking twice:
>
3) I like the idea, how about "Vouchered Accessions" rather than "Vouchers" (some of ours have 2 or even 3 against them!!!). Could be based of accession where vouchers.id != 0 and the inverse "Unvouchered Accessions" accession where vouchers = Empty. This I would definitely use. Then "Plants Propagated From" with plant where propagations.id != 0. Would mess with the formatting a bit as they wouldn't fit the grid but they could just sit as three extra elements below it maybe?

I like it because our Living Collections Policy states that we will work towards achieving a 100% vouchered collection.  So it is something that we judge ourselves by and I know a lot of other BGs do also.  It would be good to have it visible immediately after opening.  Am happy to differ to you on this one, but I know what you'll say.... I'm going to fill up all those stored queries quickly!! :laughing:

**Comment by mfrasca** [comment]
I don't know if I should mention the possibility... but it is technically possible to have buttons labelled with a name and a number (name of the query and count of the result), then with a tooltip like an explanation of the query and then the query that is executed when you click on the button... could do this for queries that do not fit in the 2 or three columns matrix.

**Comment by RoDuth** [comment]
Hahaha :laughing: !!!
>
I don't know if I should mention this... 

Why??? Because you know its more work for you because I'll want it!!  :anguished:

I do like it though!

So... waiting in anticipation for the stored queries...  What is your vision for how they'll work?

**Comment by mfrasca** [comment]
too bad for me if I think this is cluttering.  I realize it's important information so we:

1. show it
2. make sure it's not cluttering

in the above order, not first aesthetics then functionality.
