### ISSUE TITLE
general interface questions

### ISSUE THREAD

**Issue by tmyersdn** [Bauble/bauble.classic#245]
Hi @mfrasca  & @RoDuth - just a few basic questions while I learn to use the interface

1) hover text - is it possible to add mouse hover text to a few of the home screen features, eg the icons and search field?

2) search results - is it possible to add options to how search results are presented, ie if you want more or less details to be shown? ie more fields to be listed alongside the ID field. Also, would it be possible to add a tool that can generate a preset standard report from search results, eg if you search on a set of plants, it might be useful to add a button that hyperlinks to creating a report giving fields such as number of plants, condition, location?  Apologies if this is already a feature that I have missed?

3) pictures
when you choose an image file, would it be possible to also link to a url image repository?  This is not critical, but we are current not allowed to set up a formal in server folder for images (due to memory issues), so web storage is the next option.

4) insert accession tool
The "+Add" button for new species does not seem to work. Obviously you can work around this by adding species separately before adding accession (as the hover text says), but thought I should ask if the Add tool is disabled?

5) Propagation Editor
Is it possible to add propagation types?

6) Propagation locations
When you start a propagation as seed, you enter location as free text, or select from existing list. In some ways this is useful, but would it not be better to use the same list of locations as is used in the main plants window?  I am guessing these lists are locally maintained in data for each window?

7) location editor
what is "danger zone"?

8) Accession Editor Location Details
silly question, would it be possible to add a Google maps (or similar) tool to click and capture latitude and longitude data? Just as a lazy way of adding coordinates?

Okay, sorry for the jumbled set of questions, more to come!

**Comment by tmyersdn** [comment]
@RoDuth - Ross, how to keep track of the editing done by your staff in Bauble?

**Comment by mfrasca** [comment]
Bauble has a very radical choice of writing EVERYTHING that ever changes into a `history` table.
you can't really directly query the history: it is used to show changes regarding individual already selected rows.
at the moment, if you want to know what has changed recently, you can do something like:

`accession where _last_updated > |datetime|2014,3,15|`

the above gives you information about `accession`, you need do the same for `plant`, `species`, etc.
such a query you have to write by hand, it cannot be produced by the QueryBuilder.

**Comment by mfrasca** [comment]
> what is "danger zone"?

:lollipop: open the expander and you will see.
you get the chance to **merge** two locations.
it's such a destructive operation that I did not know in which other way to flag it as potentially dangerous.

the use of this option is when people make typing mistakes and create two or more locations that are really the same one!

**Comment by mfrasca** [comment]
> 1) hover text - is it possible to add mouse hover text to a few of the home screen features, eg the icons and search field?

I guess so, I'm generally afraid things get quickly cluttered, but I must say that it lasted me quite some time before I realized the button left of the search string was the Query Builder. I had broken it while getting 1.0.12 up and running in January 2014, so it did nothing and it had no hover text telling me what to expect from it.

**Comment by RoDuth** [comment]
@mfrasca My vote is for the hover over text, but keeping it simple.  Definitely agree about not over cluttering.

For keeping track I have 2 methods (now 3 with the date stamp option).
`accessions where id > 155` or similar, because I have a fair idea of what is happening it seems to work.  Just work my way back if I need to.
I have a piece of software called `SQLite database browser` and I have a look in the history table.  Generally only use this in a pinch as I don't have it on my work computer so I need to take it home with me, only use it if I have reason for concerns.

As for 2) not sure I've got you right but in the info pane (right hand side) you can collapse and expand any section using the triangles the same as you do on the left hand side.  As for reports there are a few templates and style sheets in the files that come with Bauble `~.virtualenvs/bacl/lib/python2.7/site-packages/bauble-1.0.55-py2.7.egg/bauble/plugins/report/` (is this right @mfrasca ? I always drag them out to another folder) and there is now a place for us to upload style-sheets to online that Mario has just created here https://github.com/Bauble/bauble.classic-reports.  While its a little bit of work to get set up once you have them going its just a click or 2 away.  Writing the style sheets is the thing I struggle with but its actually a very powerful, extremely customisable system... if you have some who is a little handy with Mako or xsl scripting :smile: ... Which is why it should be handy to be able to share them, I don't have too much trouble "re-cycling" a style-sheet (as in editing it to change it for my needs) its creating one from scratch that I struggle with.  I have thought that it would be nice to have a GUI for this but I can understand how that could also be very limiting and a lot of work to make.  Maybe just a very simple one for selecting fields for a csv would be nice and very handy?

3) Funny isn't it, my IT dept. prefers I not use cloud based!!  You may remember the old version had a Picasa system for pictures, never used it and was glad when Mario changed this.  You could always store a url as a note or something?
 
5 & 6) have only just started looking at the Propagations tab as we have never had the facility until recently.  I'm happy with the free text field for locations (for us I'm happy to keep a separation between the garden locations and nursery)and wont comment further than to say the types available (seed, cutting, other) would most probably suffice for my immediate needs.

8) assuming your meaning the Source>Collection>Location Details fields... I do use Google maps for this purpose, would be a great function to have... but my bigger issue is the bulk editing one...  If I collect 20 ferns all from one small section of a creek bank then I have to enter all this collection data individually for each one.  I would love to be able to "cut and paste" a whole record for this sort of thing (see issues #180 #159) then just edit the slight differences.

Keep 'em coming @tmyersdn ... I remember what it was like when I first started using it :smile:

**Comment by mfrasca** [comment]
>  As for reports there are a few templates and style sheets in the files that come with Bauble `~.virtualenvs/bacl/lib/python2.7/site-packages/bauble-1.0.55-py2.7.egg/bauble/plugins/report/` (is this right @mfrasca ? I always drag them out to another folder)

you missed a slash at second place, otherwise that is indeed the place where it gets installed, but note the version number in the path. it is better if you grab them directly from your git checkout, at
`~/Local/github/Bauble/bauble.classic/plugins/report/`

grabbing them to an other folder is good practice. :+1:

**Comment by mfrasca** [comment]
@tmyersdn 
> 3) pictures
when you choose an image file, would it be possible to also link to a url image repository? This is not critical, but we are current not allowed to set up a formal in server folder for images (due to memory issues), so web storage is the next option.

@RoDuth 
> 3) Funny isn't it, my IT dept. prefers I not use cloud based!! You may remember the old version had a Picasa system for pictures, never used it and was glad when Mario changed this. You could always store a url as a note or something?

yes quite interesting.
what do you expect Bauble to do if you put a note containing a URL of a picture?
like you enter —sorry if initially this has to be totally manual— a note with category `<picture>` and as text a URL and Bauble grabs it from the net and shows it as if it was a locally stored picture.
it's not even that difficult to program, I estimate...

**Comment by mfrasca** [comment]
@RoDuth 
>  I have a piece of software called `SQLite database browser` and I have a look in the history table. Generally only use this in a pinch as I don't have it on my work computer so I need to take it home with me, only use it if I have reason for concerns.

I think it would be quite practical, looking at the history from the `:history` command.
the difficulty I see would be in limiting the amount of data one gets from the database!
could be: grab a hundred initially and a hundred more every time the user scrolls so that the bottom comes in sight.
(by the way: there is already a `:history` command, it's just not completely implemented)
(`AttributeError: 'History' object has no attribute 'tablename'`)

**Comment by mfrasca** [comment]
about **2**, I hope you don't mean you want to change things in the main left-hand-side pane. I think it would have a huge impact on code and aesthetics.
otherwise, if you can be very specific to what you miss, per type of object, because that is the way it works in Bauble. to have it user-configurable, no, I'd rather not.

**Comment by mfrasca** [comment]
about **8**: I would keep this for a web-based version. whenever it comes and however it's written. but as long as we are desktop based I prefer not even think of it.
programming the geographic awareness first here then web-based is a no-go as far as I'm concerned.
my road map:
1. make sure the desktop "classic" stays maintained
2. write a web application as a view on the data
3. immediately include geographic data details to the web view
4. allow users to edit the data from the web interface
in my view it is: (1) - constant; (2+3) as one task; (4) not urgent.
but it will be difficult to keep doing 1 and start 2, 3, and 4 without an institutional backup.

**Comment by RoDuth** [comment]
Thanks for the `:history` command @mfrasca !!  That will definitely get used by me.  (And the improved `:prefs`) 

Agree with the rest also. I think in terms of the more or less info you come back to the bauble.lite issue #186 

@tmyersdn I think some of your issues have been more about documentation than anything else.  Someone like me who has spent many hours on my own playing around with it for a few years now (even delving into the background on the odd occasion - e.g. SQLite database browser and discovering the reports templates myself) take some of this for granted.  You have the ability to look at it afresh and hence would be a good test of what is missing from the documentation.  I have been compiling a list of dot points as I go of anything I believe should be documented but isn't and have one of my volunteers who has just started assisting me with data entry doing the same.  Maybe you could do the same?  While the documentation has gone from non-existent to fairly solid now we can always improve it.  ...Plus its the one thing I most probably can contribute to! (other than giving @mfrasca a headache :laughing: )

**Comment by tmyersdn** [comment]
1) hover text - @mfrasca - many thanks for adding these, they work well.
2) search results - gotcha on the workload and avoiding un-necessary changes. @RoDuth, what I am going to write next will fail your "too complicated" test (but I am coming at it from an idiot point of view)Mario, I am particularly interested in searches on plants, where all you see is a numerically sorted list of plants with names. Rather than mess around with formatting, is it possible to append some text after the name string, such as number of plants, status, location. This should not impact on architecture.  I am guessing you could grey the text to soften the clutter?
Is it possible to change sort order of search results, eg by location or by species? (or both). Ross, I can hear you say "read the instructions" - I did look!
Finally, I know this is just window dressing, it is certainly not urgent work. But my focus here is on how the database feels to a new user.

2a) Documentation - Ross, can you insert or send an example of what your dot-points looks like, and how do you get this to Mario?  Do you have process to decide what is worth raising?

3) pictures
Thanks Mario for your work on this, and both of you for your comments. Yes Ross, I am astounded at our situation.  But we do have a 30 ha garden.

4) The "+Add" button - thanks, working well now.

5) & 6) thanks, I will work through the current options with some of our staff here and see how it works for them.

7) "danger zone" - thanks Mario, this tool actually looks very useful, but understand the need to warn people.  I guess in our situation, with one records person and several garden staff, this tool would be restricted to a few trained people.

8) using google maps to locate source data. Mario, it makes sense to wait for the web version on this.

new comment

9) tags
thanks Mario, ctrl-t seems to work best to insert a tag.  How about adding "Add tag" to the control-right-click menu that you can access in the search results window (after "edit", "add plants", "delete")?

**Comment by RoDuth** [comment]
9) @tmyersdn not a bad idea, especially for the new user, is this easy enough @mfrasca?
2) I'm thinking that what you are maybe looking for is a report style sheet here?  Maybe it adds an extra step to the process but you could get your data in any format, any order you like, this way.  And quickly if you make it html?  Its almost like its the other great feature once you get it set up (which I am no expert on :smile: ).  ...Also, for quick totals you have status bar at the bottom and the purple highlighting of dead plants (those with quantity = 0)
2a) have only really just started on this after noticing some things that could do with better documented at this point they are just dot point brainstorms, anything (e.g. new functionality in the search options like the time stamp, count, sum, capitalising genus to search the binomial, etc. etc.) that comes up, as I notice it, I keep a quick note (something like: `sum, count - see issue #184 (e.g. species where sum(accessions.plants.quantity) > 20; species where count(accessions.id) > 2)`)  Will need to filter it at some point but for now its just notes-to-self, I have a volunteer who is on leave at the moment but I'm hoping that when they get back they might help me update readthedocs (see issue #212).  At least for now keep the brainstorm notes and we can work something out at some point in the future... your going to see things that you may not later.

**Comment by mfrasca** [comment]
9) the _tag object_ context menu entry idea... it's a bit difficult in the current set-up. `Tag` is implemented in its own `tags` plugin, so whereas the context menus for taxa are defined in the `plants` plugin and the ones for `Accession`, `Plant`, etc. in the `garden` plugin, the reaction to `^T` is set up when Bauble loads the `tags` plugin.
to add an item to those context menus means that a plugin (`tags`) alters something defined in (all) other already loaded plugins. and that we make sure that `tags` get loaded last, because we would be requesting an implicit dependency relationship from all other plugins.
well...
you can open an issue,
but you have `^T` :pray:

**Comment by mfrasca** [comment]
2) @tmyersdn you mean:
- you select plants, something like `plant where sum(quantity) > 10`, or maybe `plant like %`
- you get this potentially huge list of rows in the results view
- on the bottom status line Bauble is busy "counting"
- when you select a plant, the info pane will show you location and quantity
- but you want these data **without** needing to select the row
- you want to see these (quantity, status, location) on the plant itself, like in:
![untitled](https://cloud.githubusercontent.com/assets/122869/12115928/fd2e0042-b383-11e5-81a4-c387690c4133.png)
or
![untitled](https://cloud.githubusercontent.com/assets/122869/12116052/f284b3a6-b384-11e5-83b8-35d8810b21e2.png)

if this is what you're asking, it's not difficult for me and hardly any extra workload for Bauble, and I don't consider it cluttering, .

if on the other hand you're asking a searchable overview of these data, then it sounds like you want an export to a spreadsheet.

**Comment by mfrasca** [comment]
> 4) The "+Add" button - thanks, working well now.

@RoDuth do you realize what the above really means?
user updated to latest release (and the whole process behind it)

@tmyersdn  :+1:

**Comment by mfrasca** [comment]
> 7) "danger zone" - [...] this tool would be restricted to a few trained people.

you mean you would expect Bauble to restrict use to specific users? this is not implemented and not really available with sqlite (no user management).

if you do use a real database (other than sqlite), then users need log in and I could hide the whole danger zone. but still it's not implemented yet.

or you just tell "normal" users please to stay away from the danger zones.

**Comment by RoDuth** [comment]
>
@RoDuth do you realize what the above really means?
user updated to latest release (and the whole process behind it)

I know... and no problems!  Good to see that there were no issues with the admin authority etc...

**Comment by tmyersdn** [comment]
@mfrasca, thanks for your explanation of the tags plugin, sounds like a spider..

For sake of further discussion, I will raise the tag question (9) above as an issue, but realize the ^t function means it is not critical.

**Comment by tmyersdn** [comment]
@mfrasca, will also raise question over "real databases" and multiple users - apologies again, just creating more issues...

**Comment by mfrasca** [comment]
I think this can be closed, or did we leave anything out?
in case, please reopen! thanks!
