### ISSUE TITLE
search results follow synonymy

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#254]
something strange happens and I suspect it's because search results that contain taxon A considered synonym of taxon B will always also contain taxon B.
this is surprising but possibly practical when you ask for name match, eg: `genus like q%` gives a result set starting with _Buckleya_, the accepted name for _Quadriala_.
it is surprising and hardly practical when you ask for `species where accessions = Empty` if you have just cleaned up your database and made sure all your accessions relate to the accepted names, not their synonyms. what happens here is that the synonyms are indeed included and then Bauble says "oh, you got a synonym in the result lets show you the accepted name" which is the opposite of what you want in this case. or isn't it, @RoDuth?

**Comment by RoDuth** [comment]
I see that there is an option to show synonyms in search results in `:prefs` .  Haven't played with it yet but I would think you could open `:prefs` switch `...return_synonyms` to false then re-run the search in situations like this.  I remember it because as soon as I noticed it I thought "this could be handy".  Would just have to remember to switch it back on when you do want the synonyms.
