### ISSUE TITLE
tag object context menu entry idea

### ISSUE THREAD

**Issue by tmyersdn** [Bauble/bauble.classic#260]
from #245 
How about adding "Add tag" to the control-right-click menu that you can access in the search results window (after "edit", "add plants", "delete")?
...
Okay, accepting the difficulty in working with tags, and also the need to not slow down the search time, how about the following:
> Search results include the tag ID or description text appended to the results line (currently tags appear to be invisible unless you search on them) or marked by a symbol. 
> And, if a tag is present, the "tag object context menu" includes the option of "remove tag".

@RoDuth @mfrasca, please forgive my pushing this issue, I am just curious, as tags appear to have great potential in wider workflow issues.

**Comment by mfrasca** [comment]
> accepting [...] need to not slow down the search time [...] how about the following:
> Search results include the tag ID or description text appended to the results line

:lollipop: this is exactly the perfect way to slow down things!

tags are shown below in the same smallish window as notes.
it's two different tabs. make it higher and select the pane you want to see.

as said, tags are implemented in a different plugin than the rest. I'm not so sure, but I guess it's difficult altering behaviour _across_ plugins.
there is also no dependency in either way with the tags plugin.

let me understand better what it is that you cannot do now, I'm afraid I don't see the need to change anything.

**Comment by RoDuth** [comment]
@tmyersdn I think you and I use this function quite differently...  I tag things because its a quick way to retrieve a bunch of potentially unrelated data, generally for the sake of pulling it into a report to get a csv or the like to use externally.  For more complex things I use notes which are way more permanent for me and informative. 

I'll give you an example of how I use tags:  I want a list of all the plants that need new labels.  I go for a walk with the laptop (yes I would love it to be just my mobile phone or a tablet!) as I come to a garden bed I search it (with its code normally) when I come to a plant that needs a label I select it and tag it with a tag called "label required" and either nothing in the description or just a date in case I forget to delete it later.  When I get back to the office I select "label required" from the tags menu, report from the tools menu, select my labels report template, click ok then print it (for now on label paper but in future I want to send this off to be etched in plastic).  I will then right click the tag and delete it as the job is now done.   How quick is that!

And just so you know you just select "Tag Selection" or ctrl-t to remove a tag by un-ticking it.

My favourite thing about Bauble compared to any other system I have seen is its quick, snappy way to navigate the data in logical work flows... Its lean.  Every other system I have seen is too over bloated... and in a way that I don't see the benefit of. i.e. if once a month you need a feature don't put it in your face every day of the year.  You should have to go looking for data or features like that.  It makes no sense to me to speed up the infrequent uses at the expense of the everyday uses. Day to day I need to know where a species is, what's in a garden bed, what members of a family I have and where do I have them, what happened to all the ferns we collected 6 months ago during a field trip... that sort of data.  Scrolling through lists looking for that kind of data is most probably the slowest way I can imagine doing it!  If you know what you are looking for then in Bauble with either the tags function or a quick search string or the query builder or the hyper-links feature etc. you should be able to retrieve it.  Lets not forget Bauble is not a spreadsheet and if you want a spreadsheet, reports can make you one!

**Comment by tmyersdn** [comment]
Thanks @RoDuth, ahh, I am not really a "user" as you are, but I am hoping to give some feedback on initial impressions and looking for stumbling blocks for new users. I would hope you realize that I really don't care for spreadsheets.  Tags are of course interesting to me, as they are different to what I am used to.  In this instance, I am simply commenting on a confusing inconsistency in the external presentation and feel of the tagging tool which otherwise looks good. The selection tool still has me stumped, but I have not had a good enough go with it, but ctrl-t certainly works well, and I am glad to know it can also switch off a tag.  Your point about notes is very valid and thanks for point this out. I guess the point of difference is that notes are permanent, and tags are able to work on a whole range of record types.  I am not trying to be smart about this, I am trying to understand the underlying intention, and say when it is confusing!  Hope you are getting some good beach time :)

**Comment by RoDuth** [comment]
Sorry if I get a little defensive at times @tmyersdn I just really like the some of these features of Bauble, its what in the end made me stick with it.  But... yes they do take some getting used to and yes they were a bit of a stumbling block for me when I first started and yes I do plan on trying to improve the documentation around some of these features!!  I have finally got the GitHub thing going so I'm hoping to start working on the one thing I think I can help with and that is the docs!   So do keep a few notes on anything you think isn't well explained and I will try to make use of it. 

Also, I know from other issues just how hard it is to treat the tags etc. as if they are the same as any other component, it can just brake or reduced the functionality.  Limiting you in what you can do with them.

When I say tags are more temporary what I mean is, they don't have to be by nature or anything its just the way I tend to use them.  I think of it as allowing me to create a search that is impossible to achieve.  If that makes sense?  Manually going through and selecting things then being able to recall that list when ever you like, no mater how seemingly unrelated the combination is.

While I'm glad you don't want Bauble to be like a spreadsheet I do think they have there place and being able to get a csv out of Bauble via the report system is something I really want to work on.  I just think that the report system is just such an amazing and potentially flexible tool but it is a shame that its not so user friendly... and the sort of thing I mean when I say "brake or reduced the functionality.  Limiting you in what you can do with them." if you try too much to make them user friendly to everyone... but there must be a balance.

**Comment by mfrasca** [comment]
@tmyersdn - when you say »Search results include the tag ID or description text appended to the results line«, this is technically difficult apart from slowing down. I'm afraid I'm not being clear enough when I say "tags in different plugin". the function that computes the two lines that represent an object in the Search Results is a member function in a class, defined in a plugin (it is called `search_view_markup_pair`) and not all classes implement it. `garden` (accession, location, source, etc) and `plants` (taxonomic info) are two plugins which know of each other. the `tag` plugin is apart, it can be applied to whatever else and can be removed without impact on functionality. I would not really know how to make it alter the various `search_view_markup_pair` adding tagging information.
I think you could think of tags as a sign sticked on the back of an unaware object, it might even say "kick me".

**Comment by mfrasca** [comment]
I think this has been absorbed into Ghini/ghini.desktop#27, [28](../../../Ghini/ghini.desktop/issues/28) and [33](../../../Ghini/ghini.desktop/issues/33).
if you think anything is left here undiscussed, please reopen.
