### ISSUE TITLE
Why another collection manager application

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#272]
@RoDuth , @tmyersdn , on http://bauble.io there's a question with answer which do not match according to me.
> **Why another collection manager application?**
At Belize Botanic Gardens we felt that the other collection management software was either too expensive, inadequate or only supported Windows so we decided to create our own. 

my reaction to the question is totally different, but I would not know what you think of it.

»What do you mean "another", there is no other, nothing around that compares to Bauble. You might mention BG-recorder as gratis solution, but it's a gratis which is not free and only runs on MS-Windows if you also have MS-Access. Moreover, it has been abandoned longer than 10 years ago. The rest is proprietary and expensive.«

**Comment by brettatoms** [comment]
Seems like you're trying to incorporate the answer into the question.  If the question was "Why another free collection manager that also runs on Linux?" then yes it would be a silly question.  If you take into account BG-Base, IrisBG, BG-Recorder, BRAHMS, Atlantis-BG, etc. then it make sense.  

The answer could also include unique features of Bauble but at the time the absolute reason for starting Bauble was because I needed something free and ran on Linux.

**Comment by mfrasca** [comment]
they're all proprietary, isn't it? BG-Base, IrisBG, BG-Recorder, BRAHMS, Atlantis-BG, ...
and agreed: I am implicitly including the "free" and "cross platform" in the question while it's not an obvious requirement.

**Comment by mfrasca** [comment]
so, if we want history in the answer, we could say that in 2004 there was from the BBG a requirement "free" and "runs on Linux"?

**Comment by mfrasca** [comment]
what about:
»Bauble is not just _another_ collection manager application, it is the only cross platform free and maintained such program around.«

**Comment by brettatoms** [comment]
Yes, they're all proprietary but again, the question isn't, "Why another non-proprietary collection manager application?".

I guess the question more answers, "Why was the Bauble project started?" or "Why was Bauble created?"  Are you trying to answer, "What are Bauble's features?"?

**Comment by mfrasca** [comment]
in the answer to the question (which I copied from the bbg site) I would like to stress the uniqueness of the project.

**Comment by mfrasca** [comment]
no, no, I'm fine with the wording of the original question (**Why another collection manager application?**). I just feel we could review the answer after so many years.

**Comment by mfrasca** [comment]
an other question which I have indeed heard frequently: 
> **why should I want to use Bauble?**.

**Comment by brettatoms** [comment]
I think the question of what makes Bauble unique or why would you want to use Bauble should be implied by the Features section.  You shouldn't have to to explicitly state and answer every question a user might have while visiting the site.  I think it should be more implied by the content and design of the site otherwise every header is just a question and becomes overly verbose.   E.g. I think the "Features" header implies, "these are features that are unique and special to Bauble".   Putting the feature list in the FAQ would be redundant.

**Comment by mfrasca** [comment]
I don't know. Being open source, we also already mention that in the features. Bringing your reasoning (Putting _xyz_ in the FAQ would be redundant) to the extreme, we could also just remove the FAQ.
@RoDuth , @tmyersdn , you have an opinion on this?

**Comment by tmyersdn** [comment]
@mfrasca @brettatoms @RoDuth 

Mario, I think the FAQ is fine, you could also say Bauble actively encourages and values community input and open development.

The changes to bauble.io are looking good, I really appreciate that you have added the screen shots and videos.

**Comment by RoDuth** [comment]
I agree, looks good.  I think the question and the FAQ is fine the way it is... Plus, obviously it is accurate if @brettatoms testifies it is the reason why he started, but (as @tmyersdn said) the addition of something like "Bauble actively encourages and values community input and open development" somewhere in the mix is a good idea and I'm sure none of us would disagree with that statement!  Maybe there is space for another Q & A to the FAQ e.g. But why GPL open source??

On another note, the page could do with an update on the screenshots.  I forgot that Bauble ever looked like that!  I can't see any reason to keep the old v0.7 shots.  And the old documentation for v0.9, is it really still needed?  Is anyone still using that old a version?  We have come such a long way since then. (Thanks @mfrasca :smile: was worried it would never progress for a few years back there)

Also 
>
Bauble can export data in CSV or Access to Biological Collection Data (ABCD) format. We intend to support other standard formats such as DarwinCore, ITF2, BioCASE, TAPIR, etc., as soon as time and money becomes available.

what about the JSON and XML export formats? (but also, are BioCASE and TAPIR actually export formats per se??  May not be the best way of saying it?  @brettatoms you may be the best person to expand on this, what you were aiming for and if you still think it relevant.)

Can I also suggest the you could include "private collectors" or something similar in the first section of the page e.g.
>
It is intended to be used (and it is indeed used) by botanic gardens, herbaria, arboreta, private collectors, etc. to manage their collection information. 

I reckon if there was some way to check who is actually using Bauble and why you would find there are some out there that are using it in this way and their input here could be invaluable.

**Comment by brettatoms** [comment]
At the time I wrote that JSON didn't exist and XML is a more of a language than an export format, i.e. ABCD is a export format written in XML.

Otherwise, I don't really have an opinion about what's still relevant but thanks for asking. ;)

**Comment by mfrasca** [comment]
ok, thanks! I will dig a bit deeper into that part and consider what you write here. in the meanwhile I've a new commit to this. still thinking about the FAQ.
