### ISSUE TITLE
stored queries

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#36]
some queries are complicated enough that the user might want to save them, giving them a name and a description.
for example: 
- plants which do not yet have pictures associated to them.
- plants/accessions in CITES=I or CITES=II species.

**Comment by mfrasca** [comment]
by the way: bauble includes a query builder, which is documented but not functional.

**Comment by mfrasca** [comment]
a thought while considering issue #132 ...
implement this as the **_new tab page_** in more recent web browsers.

**Comment by mfrasca** [comment]
@jhonFitzgerald , tenemos que mirar como combinar lo que hicieron con la página inicial en que ahora hay espacio para 10 'stored queries'. también como **no** duplicar código.

**Comment by mfrasca** [comment]
@jhonFitzgerald , no he activado el código que escribieron pues hay varios detalles que no están bien y que con gusto les comento a todo el grupo, cuando quieran me contactan para que nos veamos en la uni.

**Comment by mfrasca** [comment]
@RoDuth, do you think you can help with some relevant searches you would like to see included per default.

**Comment by RoDuth** [comment]
Not really sure what your looking for...  Things that I would like to be able to do but currently can’t?

* similar to yours above really - all plants planted in the last financial year or calendar year or a certain month or 2011etc. (This one raises another issue that I will create #233...  There is nowhere to store a planting date.)
* I would also like to be able to get more figures in general out of a search.  i.e the number of living plants or the number of species.  Down the very bottom right of the window, where you see `10 search results`, could this contain more info?  something like `10 search results (containing: 12 species; 20 accessions; 30 plantings; 35 living plants; 12 locations; 3 sources)` would be very handy for all kinds of searches.  (Not sure if this is even possible and if it is whether I should raise it as a separate issue.)
* I would like to be able to search for the blanks, if that makes sense?  i.e. what accessions do I have that **don't** have a verification level recorded, or don't have any vouchers yet or haven't got label distributions or a source or provenance data, etc. etc. I've tried `accession where prov_type = "None"` and other similar approaches but I just get errors.  There most probably is a way to do it I just don't know what it is.

As for the search strings I currently use and would consider saving...  I currently have a text file I keep a few handy in.  e.g.:
* `accession where species.label_distribution like "%CQCB" and plants.location.code = "09.04.04"`  - the local natives from a certain garden bed
* `plant where location.code = "01.05.03" and accession.source.source_detail.name = "SGAP Mackay"` - plants from a particular supplier in a particular garden bed.
* `accession where vouchers.herbarium = "MRBG"` - plants we have vouchers for.
* `contact where source_type = "Expedition"` - list of our collection trips (mainly because I always forget how to do this one)
* `species where accessions.plants.quantity > "0"` and `accession where id != "0"` - because I use them so often

Fairly straight forward most of it, would just be handy to have a few saved to speed things up at times.  Either because I use them so often or I don't and can't remember when I do need them.  I normally just paste them in and change the values if I need to.

In general I think the search functions are one of the big strengths of Bauble and the query builder is great for a layman like myself.  I always thought that it would be good if the query builder could stay where you last had it each time you open it and have a `clear` button to reset it.  So that you could use it to generate a search then open it back up and its in the same place you left it so you can add extra criteria to "narrow the search" so to speak.

Sorry that ended up a little long winded, not really sure what you're looking for.

**Comment by mfrasca** [comment]
no, no, the above is fine. you start broadening the view then went to the point.
I need to hear from users what is their current practice, so what I add to the software matches that.
the part »I normally just paste them in and change the values if I need to.« is what I think I will implement.

**Comment by mfrasca** [comment]
@RoDuth wrote:
>So... waiting in anticipation for the stored queries... What is your vision for how they'll work?

I have been writing some code so you can store the queries in the `bauble` table (from Python: `BaubleMeta` class). that is a dictionary associating a name to a value.
the value we split in three fields: 
- label — shown on the button, possibly with a trailing ' - n' where n is how many objects would be shown in the result. 
- tooltip — shown when you hover over the button
- query — the search that is executed if you click on the button

the above is already in place and works if you checkout `master`, pull, install.
you need insert the data by hand though.

I have trouble imagining the user interface. I want it to be recognizable, "unsurprising". my first attempt looks dreadful.

my current idea ... wait, I have to make a picture then will post it here.

**Comment by mfrasca** [comment]
something like this I would accept myself.
![untitled](https://cloud.githubusercontent.com/assets/122869/12074996/4d7bfc44-b13f-11e5-9ac0-78cba22a4c77.png)

**Comment by mfrasca** [comment]
thinking of the MVP structure we already have, we could associate the widgets in the view to computed properties of the model. pushing one of the push buttons would tell the model how to compute the property, that is, which storage is to be shown and edited.

**Comment by mfrasca** [comment]
still todo:
- when modifying the label, the toggle button label also should follow.
- when closing the window, the home page should also be updated (you can force it).
- the label in the toggle button should be heavy when the button is active.

**Comment by RoDuth** [comment]
I like it @mfrasca!  Looking good.

**Comment by mfrasca** [comment]
it does look good to me too. :blush:
