### ISSUE TITLE
users can insert names ending in whitespace

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#55]
_From @mfrasca on April 4, 2015 20:28_

it is possible to define objects (genus, family, ...) whose name ends or starts in whitespace.
this is obviously a user error, so we should either auto-correct it or refuse to insert the value.

_Copied from original issue: mfrasca/bauble.classic#43_

**Comment by mfrasca** [comment]
closing it because I do not know which other cases could need correction.
so provide a counter-example and reopen in case.

**Comment by mfrasca** [comment]
start with an empty database
- select Ixora genus
- add a species
- type a space in the epithet field
- press OK

or:
- type a space in the epithet field, then delete it
- press OK

**Comment by RoDuth** [comment]
see my comments in issue #163 and #179 re: these allowances in ITF2 for whitespace in the species field:

```
1.2
If the plant represents a new species which has not been formally described, sp. nov., sp. A,
sp. 1 (or other acceptable codes) should be entered, if possible followed by a unique
identifier, such as the collector's name and number or the locality.
3.
If the Infraspecific Hybrid Flag is H, the entry in the field must be a Hybrid Formula, with the
lowercase letter 'x' between the species epithets of the two parents, e.g. dichroanthum x
griersonianum for Rhododendron dichroanthum x griersonianum.
If only one parent is known, then enter the specific epithet of that parent alone (without the lower
case letter 'x').
```
Both of which we currently use at work on an older version of Bauble...

**Comment by mfrasca** [comment]
I'm sorry, indeed it seems too rigid, having removed _tout court_ spaces from species epithets.
my reasoning was and still tries to be based on constructing the hybrid formula you describe in #179 .

the `×` as a binary operator and two species as operands.
or as a chain of _n_ `×` operators and _n-1_ operands, if their role is not better specified.
operands being species that are already in the database.

but this is **currently** not within our possibilities and you're using Bauble 1.0 and you point me at the consequences of some excessive decisions I've taken. sorry about that.

apart from the spaces after or before the epithet that I can strip away,
spaces in species epithets allow less careful users to write:
»coccinea var. militaris« all in the species epithet.
while only coccinea belongs there, and the rest goes into infraspecific information, var. as the rank and militaris the epithet.

-----------------------------------------------
looking at the text you quote:
`1.2` is not a problem because you put that in a infraspecific unranked epithet entry and there's no space removal there. can you confirm?

the other point is more complicated, at least in 1.0. and forms —I think— a different issue, again related to hybrid formulas. please follow me there (#218) and help me see where my reasoning does not solve the problem I just caused!

**Comment by mfrasca** [comment]
in an existing species: if you are using your species epithet for a hybrid formula, that is, if your species epithet already contains a `×` symbol, then spaces will be honoured.
in a new species: no spaces allowed unless you start typing an hybrid formula.
you do not type the `×` directly, you use the `*` sign, replaced by space-mult-space.

limitations:
you cannot insert a `*` symbol in the species epithet.
you can type the × directly, but then you will need go back one char to insert the preceding space.

**Comment by RoDuth** [comment]
@mfrasca no worries, I blame myself for not thinking of it at the time.  As for the `1.2` quote...  You are correct we do currently use the infraspecific field for `sp. nov.` and the like, but upon re-reading the ITF2 species epithet section I see that its not ideal, but the likeliness of this causing issue for us at this point is remote. The `*` approach you describe sounds like it would work fine for now.  

This has made me think about some of these non-standard naming issues and seeing if any of the standards refer to them and offer solutions.

**Comment by mfrasca** [comment]
On 13/12/15 06:26, RoDuth wrote:
> upon re-reading the ITF2 species epithet section I see that its not
> ideal, but the likeliness of this causing issue for us at this point is
> remote

in my opinion: a transfer format should not dictate into too much detail
one's choices in internal data organization.

According to me Bauble should write unranked infraspecific information
into the species epithet field in ITF2 export and when importing ITF2
information ... wait, there is no ITF2 import/export in Bauble! !!

so what are we talking about? :D

do you want to open an issue on supporting ITF2?

part of this support is holding compliant fields (what we have been
discussing here and elsewhere), and/or the ability to import ITF2
compliant information into Bauble so that when exported you would get
the same you had imported.

**Comment by RoDuth** [comment]
My concern here is more about compatibility in general than the ability to do a full ITF2 transfer per se.  I say "its not ideal" but its not something that is likely to be encountered commonly so its no big deal.  Can I ask though, what issue was the whitespace causing for users?

As far as compatibility goes, I know I keep bringing it back to ITF2 but this is only because it is the most directly BG relevant standard in common usage going and because it is much more explicit.  From a bigger picture perspective I think ABCD is most probably more important but from what I see it doesn't tend to digress from ITF2 too greatly and hence ITF2 becomes the easier reference.

I would still like to think that when we share plants, seeds, propagules, etc. with other institutions we should be able to quickly and easily transfer the relevant records...  How that is achieved isn't of great concern, a csv dump and someway of importing the bits you want would suffice.  I'm about to receive a delivery of plants from the [ANBG](https://www.anbg.gov.au/) I'll see what data they send and look at it again then.

Currently there has been talks within Australia toward a shared BGs database (similar to BGCI PlantSearch but with much more detail, such as, the number of living plants, the collection location data, etc.) with an aim of conservation and research.  This could be an example of what I meant when, in issue #163, I said:
> for us smaller, under resourced gardens I feel that adherence to these standards adds great value to our collections by making them more easily accessible.

Then there are those that are currently using ITF2 compatible systems (e.g. BGRecorder) that may be considering moving over to Bauble, the easier and more pain free that migration is the better.  Particularly if it is something they can achieve themselves.  Then once they have transferred they will bring their approaches to data entry with them no doubt.

In my opinion, and particularly looking to the future, there are just too many good reasons to adhere to the standards wherever possible.

**Comment by mfrasca** [comment]
I agree that removing spaces altogether, as I did, is a couple of steps further the title of this issue #55.
>  Can I ask

I have seen database entries _ending_ on a space, or _starting_ on a space, then things like 'ficus indica', which is not the same as 'ficus-indica' (that is: for each single name I have seen as many as three or four variants where the mistake was introduced by allowing spaces at beginning, end and in the middle.) (this happened after an initial import from a spreadsheet, where —as it happens— such mistakes are extremely easy to introduce.)

ITF2, Species Epithet, Rule 1 and 2:
> The specific epithet must be one word [check the exceptions].
> It must consist of lowercase letters (a‑z), and may contain one or two hyphens

IIUC, the exceptions are related to botanist's flags (for possibly new species) and hybrid formulas.
Still IIUC, I would keep this solution as it is, ask you if you are fine with having to write the botanist's flag in an unranked infraspecific epithet.
I hope to implement it more clearly in the next Bauble 1.1 line, where I should offer you not only a multi-way hybrid flag (Ø, H, ×, +) but what about a `sp.nov.` flag, so you tell the software that now the species epithet has to comply to other rules than the above 1 and 2? (in case you agree, would you mind opening a new issue?)

> I would still like to think that when we share plants, seeds, propagules, etc. with other institutions we should be able to quickly and easily transfer the relevant records... How that is achieved isn't of great concern, a csv dump and someway of importing the bits you want would suffice. I'm about to receive a delivery of plants from the ANBG I'll see what data they send and look at it again then.

I'm very curious to see an interchange format you use in real life.

A csv dump as it is now implemented by Bauble is extremely useful when copying a Bauble database to a user who wants to accept it into an empty database—using the same SQL engine—, but otherwise hardly of any interest to anyone else. this is the reason why I introduced the JSON import-export, which has its own disadvantage of being painfully slow.

@RoDuth , can you make a list of your favourite issues, in decreasing order of relevance and urgency?

if I understand you correctly, you want to open an issue like "please achieve ITF2 compliance".

let's hope the project with the UNAS goes well, then I will have a team at disposition. I don't see how to do all this on my own.

**Comment by RoDuth** [comment]
I'm not sure I want to necessarily *enforce* the ITF2 compatibility issue so much as not drift away from it and if anything fall in line a little more in areas where this isn't too hard to achieve.  I see this as a field by field issue more than a global issue.  Something that I think you just need to keep an eye on as you go.  As I notice any issues I will endeavour to point them out.  In terms of urgency I'm not sure I haven't found a workaround that is acceptable for me now (this, now largely fixed, issue of basic hybrid formula being the biggest issue I have had so far) so I don't want to overly emphasize any one point.  

And yes, I will admit that as many gardens deviate from ITF2 as adhere to it but what better guide have we got?  I will be interested to see what format we receive from ANBG, I have asked them today if they could send me any examples to share.  Will post them here or at worst email them to you @mfrasca.

(In terms of urgency can I add that I am only using the most recent version at home and have not yet upgraded at work due to the lack of a global install option for windows, this would be my most pressing issue right now in terms of work.  I have several people who log into my workstation and use Bauble)

Everything you mention above re:
>ITF2, Species Epithet, Rule 1 and 2:

is spot on, no issue here, I totally agree with your suggested approach.

When I say csv dump I'm more thinking about the kind of output you can get from the reporting system (where you only output selected fields from the search results, etc.) just there is no way of importing this at this point.  (e.g. If I have a batch of seedlings from a known collection source and I use half of them for a new accession for us and give the other half to another garden, I can pull our records up in Bauble and generate a report which provides our accession number, all the collection data and any other fields that may be of relevance to the receiving garden.  Then when they get it, if it is in some universal format such as csv, they could import it into their database when they generate their accessions) And in this context I say csv only as it is so universally used.  Its more the scenario that interests me and from our discussion the other day I think I remember you talking along the same lines in regards to the use of JSON.  I have absolutely no JavaScript or JSON understanding so wont proffer a solution here but is there a way to make the 2 work together?  I think most systems are able to produce a basic csv - can this be transformed, say using a script for instance, into JSON?  Anyway, I'm out of my depth here, you get the point.  Just looking for as universal a solution as possible.

**Comment by mfrasca** [comment]
my point of view is that (when dealing with forgetful people like me, but also when developing code that could be edited by others later on) the only way not to drift from something is to enforce it. all these ITF2 rules should be documented in balloon texts (tooltips) and included in unit tests, respectively for the user an the next programmer. #217

**Comment by RoDuth** [comment]
That is a good point.
