### ISSUE TITLE
does Voucher belong to accession or species?

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#58]
_From @mfrasca on April 29, 2015 20:30_

during a review, Felipe was a bit surprised to see the Voucher in an accession tab. he explained what a voucher is, the term does not get translated into Spanish, and if we understood each other well, then the Vouchers should be associated to a species, not to an accession (an identification of a plant).

_Copied from original issue: mfrasca/bauble.classic#78_

**Comment by mfrasca** [comment]
in a further interview with Luis Baquero, I understand that a voucher can be used to identify a species in case one does not want to define a species but is very much convinced the voucher is relative to a new species. so he would like to be able to refer to a new species (sp.nov.) which is not further defined than by a voucher, and the voucher name would immediately follow the 'sp. nov.'

check issue #85 as well.

**Comment by RoDuth** [comment]
my understanding is that a voucher DOES belong to an accession.  It is used to confirm identification of the specific plant from which it was taken and also for the sake of back tracking from the herbarium record.  This would make the accession a level 2 or higher verification ("the name of the record confirmed by a taxonomist... using herbarium...") in the "Verifications" tab of the "Accession Editor" and a voucher would then be attached to the record.  Other accessions of the same species that may be in the collection could then be marked as a level 1 verification ("...determined by comparison with other named plants") with the vouchered accession's number in the reference field to show which accession it was compared to.  Unless, of course, further voucher specimens where taken (which is ideal, especially if other accessions were from different sources).  

Some Botanic Gardens have accession policies that state that almost no accession is accepted into the collection without a voucher from the donor plant.  In these gardens back vouchering (i.e. taking an herbarium-sample/voucher from the plant AFTER it has been growing in the collection) is considered only in special circumstances (e.g. where difficulties exist in sourcing the correct ID material for the herbarium sample at the same time as the seed for propagation).  In these gardens every accession will have at least one voucher in every accession with the idea that all plants are at least level 2 verifications.  While our policies are not quite so rigorous we use it in this way so please don't change it's location in future releases.  I hope that made sense!

**Comment by mfrasca** [comment]
it does make sense, but it still confirms my impression, let me see if I can explain how I see it:
(http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4103463/)
in my understanding, a voucher is represented in the database by mostly textual information, all that is needed to visit the place where the voucher is kept and find it, as well as possibly one or more pictures of the voucher.

I see two places where I would expect to hold voucher information.
the voucher for the collected plant (the specimen that dies dried into the voucher) is a property of the plant; - the plant belongs to an accession (so the accession inherits all vouchers from the vouchered plants in the accession, hopefully one is enough); - which relates to a species which has information about its own exemplary voucher.

plant voucher is in your herbarium.
species voucher is somewhere else.

**Comment by RoDuth** [comment]
In our situation we try to produce 2 vouchers for an accession at the same time, one goes to the local authority for confirmation of ID (Queensland herbarium) and we ask that they keep it in there collection, the other we keep ourselves for reference so in general there are 2 vouchers attached to an accession.  In the case of disputed ID we can end up with more!  
If I have got you right the second (**2**) voucher you are referring to is the "type specimen" and this could be attached at species level.  I'm happy for the function to be there, it's just not likely we would use it.  The data is largely available online for us anyway.

**Comment by mfrasca** [comment]
so there's a voucher, and it belongs where it is now,
and there's a type specimen, which is not necessary as of now.
(possibly made useless if you add a web picture to the species).

**Comment by tmyersdn** [comment]
@mfrasca @RoDuth 
Sorry I have been quiet on this one. Been a busy time here. 

Guys, I agree with Filipe, a voucher does not belong to accession.   A voucher is independent to a living plant, it is like a photo or image.  Also, I definitely do not want to give an accession number to every wild plant that I make into a voucher, this is an inappropriate use of "living" accessions.

Finally, Mario, Luca Ghini invented herbarium vouchers before he invented botanic gardens. The two are independent, it is just that many gardens choose to have herbaria. And @RoDuth, your situation is a little unusual in that many gardens around the world do not have an affiliated strong herbarium that asks for duplicates of a gardens living collection. It is a good system, but it is definitely not universal. There are also gardens in places where the gardens are the closest and possibly only working botanical institute, so they maintain a herbarium of local wild plants. 

I would suggest, that at the very least this decision to lump vouchers into accessions is delayed until discussion with a wider user base.

**Comment by mfrasca** [comment]
about Luca Ghini and he inventing herbarium vouchers, if you have a publication to which to refer, we could add this to the wikipedia page! and no, I definitely did not know this part. :+1:

**Comment by tmyersdn** [comment]
I only have https://en.wikipedia.org/wiki/Luca_Ghini
I think it is better to say he made the first recorded herbarium, vouchers came later (?)

**Comment by RoDuth** [comment]
@tmyersdn this is definitely not unique amongst the gardens I deal with and I'm sure that @brettatoms didn't included it here because of some unique situation that only he and I happened to share!  In fact I'd go as far as saying if you were to remove the ability for me to record the vouchers I have taken of an accession and whether it was a back voucher or from the parent material I would not be able to do one of the more important things I do!  

How else do you achieve a level 2 or greater verification level?  (ITF2 vlev 2- The name of the plant has been determined by a taxonomist or other competent person using the facilities of a library and/or herbarium, or other documented living material)  Is this not something you try to achieve Tom?  When you collect a plant from the wild do you check that you have the identification correct?  What do you do if you don't know what the plant is?

Bauble is a living collection database and this is just recording a voucher number as proof of identification for a specific accession within your living collection.  Its not trying to do anything more than that.  What you are talking about is a database of your herbarium.  The same as (to use your analogy) you may have a collection of photos some where and if you have a few photos of an accessions in the living collection you may link them to that accession within Bauble but you don't expect Bauble to be your database of photographs (at least I hope you dont! :laughing: ).  My opinion is it's an extra feature and not the same issue.  I've said it before, I see no reason why you couldn't run Bauble (with a separate connection/database) as a separate herbarium database if you chose to or if @mfrasca is happy to ADD extra functionality to do this I have no concerns just don't remove this functionality...

**Comment by mfrasca** [comment]
> just don't remove this functionality

:smiling_imp:

**Comment by RoDuth** [comment]
:smile: Amongst the smaller regional gardens that I deal with, who concentrate on wild collected native plants, this is just such a critical function, and most of them don't have herbariums, they just need to record the voucher number from the herbarium they send it to.  Anything more is great (as long as it doesn't lead to a greater work load in data entry) but I don't think it will make any difference to these gardens.

**Comment by brettatoms** [comment]
The hardest thing about building a living collection manager/botanic garden database is that no two gardens manager their collections the same.  ;)

 I would think there are (at least) two use cases here, 1) Bauble is used as a herbarium management application and an accession is essentially the same thing as a voucher and 2) Bauble is used in a garden to manage the living collection and those collections are paired with a voucher at some herbarium somewhere (either their own or for some other).  We used to do a lot of wild plant collections with RBG Edinburgh and, as @RoDuth mentioned, they always left a local specimen in the herbarium in Belize.

Either way I don't think a voucher would ever be a associated with a species rather than an accession.  When you're identifying something you're not identifying every accession associated with a species.  If you have 10 accessions of a species and each of those accessions are from completely disparate sources then you don't want to change the identification of one and have it affect the other 9.

**Comment by RoDuth** [comment]
That's it! and it has just occurred to me what the difference is.  I (and @brettatoms) are seeing vouchering as proof of ID of an accession within the living collection.  @tmyersdn and Filipe are seeing vouchers as something to identify *from* (like a type specimen I guess?).  As in similar to a photo of the species that others can then use by comparison to identify other plants to see if they are the same species.  I think this is best dealt with as in 1) above.

**Comment by mfrasca** [comment]
so if we ever add this to species, we should call it `type specimen` (or at least add the text as tooltip).
I put it in milestone `future` because I do not plan doing anything of this into 1.1
the url of a picture of a type specimen, you can put in a note with category `<picture>` and I hope that @tmyersdn and @felipead87 will find it useful enough.

**Comment by tmyersdn** [comment]
you are all making sense, but not quite getting our situation here

@RoDuth, I simply mean that we have "some" vouchers from plants that are not in the living collection, ie weeds like dock, nettle or thistle. Observation of new weeds is something we get asked to do, and keeping herbarium specimens is just part of documenting these observations. Yes, we can have these stored in an external herbarium off-site. But nobody wants our weeds! :smile: And, why would we not keep them in our own herbarium.
Am happy to keep these in a 2nd connected database, but this seems like double handling, and I would want to use species name data, contact data, accession and plant data etc. I am guessing that is not easy to set up.
It is not practical for us to apply living collection accession numbers to plants that are not part of the living collection.  Also, I would not want to renumber our vouchers with Bauble/Ghini LC accession numbers. :banana: :banana:
I fully recognize your need to continue using vouchers as they are. Yes, we do send some herbarium material away, sometimes from the living collection, but not just from the living collection.

Another issue is wild plants from which seed is collected from to grown into plants. Our rule here is to assign new accession numbers to plants grown from seed. In the case of wild collection, the voucher of the parent plant would get a herbarium accession number, and the seed would get a living collection accession number.

@mfrasca, I do not mean "type" specimens for identification from. I don't think many gardens will have these, or want to enter data about them.  But I now get the issue that @RoDuth and @brettatoms raise about not adding vouchers to species.

**Comment by mfrasca** [comment]
let me quote @brettatoms, »an accession is essentially the same thing as a voucher«. which is quite exactly also my point of view. I would say that the voucher is the equivalent of a plant and relates to an accession. it's dead and dried, but who cares? it still is a plant and it is associated to the accession.

@RoDuth says: »[we see] vouchering as proof of ID of an accession within the living collection«. please compare this statement with the above. you say it this way because you have turned one of many plants into a voucher, while many minus one are still in your living collection.

but if you turn one plant into a voucher and leave the others in peace in the bush where you found them, you have accessioned only the dead and dried one.

> I would not want to renumber our vouchers with Bauble/Ghini [living collection] accession numbers

in Bauble/Ghini, you can use whatever you like, as accession code. the software suggests you a code, but you are free to overwrite it completely. or this was not your perplexity?

I have the impression we have understood each other, and I think we decided we like the software the way it is. I'm afraid the original question was due to my confusion between type specimen and voucher.

**Comment by tmyersdn** [comment]
@mfrasca - 
This possibly works, but I have another question for you
When you create a new accession in Ghini/Bauble, the software suggests a code, based on the year and a counter.  You then are asked for the type of material.

Is it possible in the type of material to add some extra enumerations: "voucher" and "seed for storage".  If either of these types is selected, then the suggested accession number gets replaced by another suggestion: (either SD.#### or H.####). In both cases, SD and H, the software would run an independent counter for SD and for H. These would not need a year.

Mario, I disagree with both Brett and Ross on how herbarium and living collections work together. But this is based on a difference in how our gardens work. I suggest that at present we do not have enough users to give a winning point of view.
