### ISSUE TITLE
support more engines (MySQL)

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#92]
Bauble currently supports, out of the box, SQLite; care has been taken to make it easy for the user to add PostgreSQL; other engines can be added, but are as of now not supported.

**Comment by brettatoms** [comment]
Just to give some context, at one point we supported MySQL but with all the little nuances between venders (e.g. unicode) maintaining support for every engine that SQLAlchemy supported was more than just changing the database connection string.  There were a lot of weird cases that made it difficult to account for.   I found it easier to choose a subset of engines and make them rock solid rather than being flexible and allowing multiple database engines.

**Comment by mfrasca** [comment]
I'm going to give a try at MySQL, just because it's the engine being used at the ‘Universidad Nacional de Jaén’. I'm not a MySQL fan and the current situation looks fine to me. but you know system administrators!

**Comment by mfrasca** [comment]
@brettatoms , you possibly still have a list of issues with mysql?
so I have an idea of what problems I'm going to face.

**Comment by mfrasca** [comment]
in db.create, `metadata.create_all(bind=connection)` stops with error:
`(in table 'tag', column 'description'): VARCHAR requires a length on dialect mysql`
